version: "3.9"
#version: "2"

#networks:
#  app_network:
#    name: lib10network
#    driver: bridge

services:

  postman:
    image: postman/newman:alpine
    container_name: postmanTests
    restart: on-failure
    command:
    #  run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT} --env-var host=api:8081 -k
      run Lib10_testing.postman_collection.json -e localhost.postman_environment.json --env-var host=api:8081 -k
      -r cli,json
      --reporter-json-export="reports/lib10RestAPITests.json"
    volumes:
      - "./:/etc/newman"
    depends_on:
      - api
      - db
#    networks:
#      - app_network

  api:
    container_name: lib10_api
    restart : always
    ports:
      - "8081:80"
#    networks:
#      - app_network
    environment:
    #  - server.port=8081
      - spring.datasource.url=jdbc:mysql://db/lib10?serverTimezone=UTC
      - spring.datasource.username=usr_lib10
      - spring.datasource.password=secret
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - db
#    links:
#      - db:db

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
#    networks:
#      - app_network
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=lib10
      - MYSQL_USER=usr_lib10
      - MYSQL_PASSWORD=secret
