version: "3.9"
#version: "2"

#networks:
#  app_network:
#    name: lib10network
#    driver: bridge

services:

  postman:
    build:
      context: init/newman
      dockerfile: Dockerfile
  #  image: postman/newman:alpine
    container_name: postmanTests
    restart: on-failure
    command:
     # - sh -c './wait-for.sh api:8081 -- run Lib10_testing.postman_collection.json -e localhost.postman_environment.json --env-var host=api:8081 -k -r cli,json --reporter-json-export="reports/lib10RestAPITests.json"'
      run Lib10_testing.postman_collection.json -e localhost.postman_environment.json --env-var host=api:8081 -k
      -r htmlextra,cli,json
      --reporter-json-export="/etc/newman/lib10RestAPITests.json"
      --reporter-htmlextra-export="/etc/newman/lib10RestAPITests.html"
    volumes:
    #  - "./:/etc/newman"
      - "$PWD/reports:/etc/newman"
   #   - newman-report:/reports
    depends_on:
      - api
      - db
    entrypoint: [ "/etc/wait-for.sh", "api:8081", "-t", "0", "--", "newman" ]
  #    networks:
#      - app_network

  api:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: lib10_api
    restart : always
    ports:
      - 8081:80
#    networks:
#      - app_network
    environment:
      - spring.datasource.url=jdbc:mysql://db/lib10?serverTimezone=UTC
      - spring.datasource.username=usr_lib10
      - spring.datasource.password=secret
    depends_on:
      - db
    #command: /wait-for-it.sh db:3307 --timeout=60
    #entrypoint: [ "/wait-for.sh", "mysql://db:3307", "--", "java", "/usr/local/lib/app.jar" ]
  #  command: ["java"]
 #   links:
  #    - db:db
    #

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
#    networks:
#      - app_network
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=lib10
      - MYSQL_USER=usr_lib10
      - MYSQL_PASSWORD=secret

#volumes:
#  newman-report: