version: '2'


##todo environnement bdd

#networks:
# app_network:
#   name: lib10network
#   driver: bridge

services:

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
  #  container_name: lib10_bdd
    ports:
      - "3306:3306"
  #  networks:
  #    - app_network
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
    #  DB_CONN_STR: "host=db;port=3306;database=LIB10;userid=usr_lib10;password=secret"
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=LIB10
      - MYSQL_USER=usr_lib10
      - MYSQL_PASSWORD=secret

  api:
   # image: maven:3.6.3-jdk-8-openj9
 #   container_name: lib10_api
    restart : always
    ports:
      # local:container
      - "8081:80"
  #  networks:
  #    - app_network
  #  tty: true
   # environment: 
    #  DB_CONN_STR: "host=db;port=3306;database=LIB10;userid=usr_lib10;password=secret"
    #volumes:
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      # Lien vers le conteneur "db" (déclaré ci-après)
      - db:db

 ## postman:
 ##   image: postman/newman:alpine
 #   container_name: postmanTests
  ##  command:
  ##    run postmanTests.postman_collection.json -e postmanTests.postman_collection.json -k
 ##     -r cli,json
 ##     --reporter-json-export="reports/fastRestAPITests.json"
 ##   volumes:
 ##     - ./postmanTests:/etc/newman
 ##   depends_on:
 ##     - db
 ##     - api
##    links:
 ##     - api:api
##      - db:db
  #  networks:
  #    - app_network
    
volumes:
  mysql-data:
    driver: local
  
