version: '2'

services:
  lib10.api:
   # image: maven:3.6.3-jdk-8-openj9
    container_name: lib10-api
    ports:
      # local:container
      - "8081:80"
    hostname: lib10-api
    #environment: 
    #volumes:
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - db
   # links:
      # Lien vers le conteneur "db" (déclaré ci-après)
    #  - db:db


  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    container_name: lib10-bdd
    ports:
      - "3306:3306"
    hostname: mysql
  #  expose:
  #  - 3307
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=LIB10
      - MYSQL_USER=usr_lib10
      - MYSQL_PASSWORD=secret
